name: test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
     # - name: Setup Docker Bulidx
      #  uses: docker/setup-buildx-action@v3
      - name: Run Tests
        run: docker compose run test pytest